# 一.ndaaray的特性

## 1.多维性：
支持，零维一维二维，类似于c中的数组

In [1]:
#引入numpy库
import numpy as np
from streamlit.hello import hello

#创建一个零维ndarray数组
arr=np.array(5)
print(arr.ndim)
print(arr)

2026-05-13 18:56:40.259 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 18:56:40.261 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 18:56:40.819 
  command:

    streamlit run D:\Users\Yu\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-05-13 18:56:40.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 18:56:40.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 18:56:40.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-13 18:56:40.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running

0
5


In [2]:
#创建1维的数组
arr=np.array([1,2,3])
print(arr)
print(f"arr的维度是{arr.ndim}")

[1 2 3]
arr的维度是1


In [3]:
#创建一个2维的数组
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(f"arr的维度是{arr.ndim}")

[[1 2 3]
 [4 5 6]]
arr的维度是2


## 2.同质性：
如同数组，里面的元素必须是相同数据类型

In [4]:
arr=np.array([1,'hello'])
print(arr)

['1' 'hello']


注意上方的1是带有单引号的，是因为同质性，所以python将1转化为了字符串

In [5]:
arr=np.array([1,2.5])
print(arr)

[1.  2.5]


同理，此时为了保留更多数据，保留了2.5，将1转换为了1.

## 3.高效性：
同样类似与数组，是在内存中连续分配的，方便查找和管理

# 二.ndarray的属性:

1. shape:数组的行列数，用法：arr.shape
3. ndim:数组的维度，用法：arr.ndim
3. size:数组的个数，用法同上
4. dtype:数组元素的类型(整数，浮点数等),用法同上
5. T:转置：行变列，列变行
6. itemsize：单个元素占用的内存字节数
7. nbytes：数组总内存占用数：size*itemsize
8. flags:内存存储方式：是否连续存储

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状:',arr.shape)
print('数组的维度：:',arr.ndim)
print('数组的个数:',arr.size)
print('数组的类型:',arr.dtype)
print('数组的转置:',arr.T)
print('单个元素的占用内存:',arr.itemsize)
print('总内存：',arr.nbytes)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
数组的维度：: 2
数组的个数: 6
数组的类型: int64
数组的转置: [[1 4]
 [2 5]
 [3 6]]
单个元素的占用内存: 8
总内存： 48


# 三.ndarray的创建

## 1.基础方法

In [7]:
#基础的创建方法
list=[1,2,3]
arr=np.array(list)
print(arr)

[1 2 3]


In [8]:
arr1=np.copy(arr)#元素和初始的相同，但是不是同一个数组，原来那个不变
print(arr1)

[1 2 3]


## 2.预定义的定义

In [9]:
#预定义形状
#全0 全1 全初始化 固定值
#1.全零型
arr=np.zeros((2,3),dtype=int)#后面这个dtype是为了变成int型，不至于出现小数点
print(arr)
arr1=np.zeros((2,),dtype=int)#创建一维的全零数组
print(arr1)

[[0 0 0]
 [0 0 0]]
[0 0]


In [10]:
#全1型
arr=np.ones((2,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [11]:
#全初始化
arr=np.empty((2,3),dtype=int)#不推荐使用
print(arr)

[[0 0 0]
 [0 0 0]]


In [12]:
#全固定值
arr=np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [13]:
#附加用法
arr1=np.zeros_like(arr)#同arr格式一样，但由于是zeroslike，所以被填充为零a
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## 3.等差定义

In [14]:
arr=np.arange(1,10,2)#开始，结尾，步长
print(arr)

[1 3 5 7 9]


## 4.等间隔序列

In [15]:
arr=np.linspace(0,10,5)#开头，结尾，份数
print(arr)


[ 0.   2.5  5.   7.5 10. ]


## 5.对数间隔数列

In [16]:
arr=np.logspace(0,4,3,base=2)##开始，结束，份数，以这个为例，3代表0到四区间内找三个数，0，2，4，以它们作为base的指数，得出的结果
print(arr)

[ 1.  4. 16.]


## 6.特殊矩阵

In [17]:
#单位矩阵:主对角线为1，其余为零
arr=np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [19]:
#对角矩阵：主对角线上非零，其他全为零
arr=np.diag([1,2,3])#填的是主对角线上的元素
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
#随机数组的生成
#生成0到1之间的随机浮点数(均匀分布)
arr=np.random.rand(2,3)#每次运行都不一样
print(arr)

[[0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112]]


In [23]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[3.76441804 5.57287659 5.84933708]
 [4.68506057 3.53634156 5.3107558 ]]


In [22]:
#生成指定范围区间的随机整数
arr=np.random.randint(3,30,(2,3))
print(arr)

[[ 9 29 16]
 [14 29 28]]


In [21]:
#生成随机数列(正态分布)(-
#两边小，中间大
arr=np.random.rand(2,3)
print(arr)

[[0.2723164  0.71860593 0.78300361]
 [0.85032764 0.77524489 0.03666431]]


In [20]:
#设置随机种子
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## ndarray的数据类型

1. bool,布尔类型
2. int8,int16,unit8,unit16,int32,unit32,int64,unit64:有无符号的对应字节的整型,字节越大表示的数越大
3. float16,float32,float64:半，单，双精度浮点数
4. complex64,complex128:用两个32位/64位浮点数表示的复数

In [29]:
arr=np.array([1,0,2,0],dtype=np.int8)
print(arr)

[ 1  0 21  0]


## numpy的索引与切片

1. 基本索引：利用整数索引直接访问元素，索引是从零开始的
2. 行，列切片：使用冒号：切片语法选择行或列的子集
3. 连续切片：起始索引到结束索引按步长切片
4. 使用slice函数：通过slice(start，stop，step)定义切片规则
5. 布尔索引：通过布尔条件筛选满足条件的元素，支持&，|等逻辑运算符

In [34]:
#1.直接使用索引
arr=np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[:])#利用冒号获取全部
print(arr[3:6])#获取区间的数据，左包右不包

[31 37  9 49 20 49 96 54 11 39 10 61 61 24 53 97 77 79 96 55]
31
[31 37  9 49 20 49 96 54 11 39 10 61 61 24 53 97 77 79 96 55]
[49 20 49]


In [36]:
#2.布尔索引
arr=np.random.randint(1,100,20)
print(arr[arr>5])#布尔索引
print(arr[(arr>5)&(arr<10)])

[26 42 10 67 16 66 31 89 50 41 12 70 59 87 38 69 19 10 58]
[]


In [37]:
#3.slice函数，类似于冒号的语法对照法一
arr=np.random.randint(1,100,20)
print(arr[slice(2,5)])
print(arr[slice(2,5,2)])#不过可以多加一个参数，即为步长

[76 24 30]
[76 30]


In [40]:
4.#二维数组的索引与切片
arr=np.random.randint(1,100,(4,8))#创建二维数组
print(arr)
print(arr[3][2])#注意索引是从零开始,取出二维数组中的任意一个数
print(arr[:,:])#基础写法，用来得到某行某列的数组，把冒号换成索引数字即可，不换就是默认全部
print(arr[1,:])#取出第二行
print(arr[1,2:5])#第二行，第三个数到第五个数，左包右不包
print(arr[arr>50])#以一维的形式，给出所有满足条件的元素
print(arr[2][arr[2]>50])#在第二行筛选大于50的元素
#对列操作也是同理

[[69 83 11 65  5 76 16 55]
 [12  5 23  7 60 45 74 12]
 [19 53 65 56 65 37 49 96]
 [59 40 38 55 93  6 27 16]]
38
[[69 83 11 65  5 76 16 55]
 [12  5 23  7 60 45 74 12]
 [19 53 65 56 65 37 49 96]
 [59 40 38 55 93  6 27 16]]
[12  5 23  7 60 45 74 12]
[23  7 60]


## ndarray的运算

In [45]:
#简单的一维算术运算
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a+3)#加一个标量，是每一个位置都要加
#对应位置的计算
#此时回顾一下原生python里面
c=[1,2,3]
d=[4,5,6]
print(c+d)
#当你不适用np.array来定义时，默认加号是拼接,减号是不允许的

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4 5 6]
[1, 2, 3, 4, 5, 6]


In [44]:
#二维数组的运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.7        0.72727273 0.75      ]]


In [46]:
#广播机制，当两个矩阵形状不相同时，但是不能完全不同，必须要符合线代里面两个矩阵能相乘的条件
a=np.array([1,2,3])#一行三列
b=np.array([[4],[5],[6]])#三行一列
print(a+b)
print(a-b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]


In [47]:
#矩阵的运算，矩阵的乘法
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a@b)#用@表示矩阵的乘法，而*表示对应位置相乘

[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


# Numpy的常用函数

In [48]:
#计算平方根注意返回值为浮点数
print(np.sqrt(9))
print(np.sqrt([1,4,9]))


3.0
[1. 2. 3.]


In [49]:
#计算指数,e的多少次方
print(np.exp(1))

2.718281828459045


In [50]:
#计算自然对数，lnx
print(np.log(2.71))


0.9969486348916096


In [51]:
#计算三角函数的值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [53]:
#计算绝对值
arr=np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [54]:
#计算a的b次幂
print(np.power(arr,3))


[ -1   1   8 -27]


In [55]:
#四舍五入
print(np.round([3.2,4.5,8.1,9.6]))

[ 3.  4.  8. 10.]


In [56]:
#向上向下取整
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))


[ 2. 26. 82.]
[ 1. 25. 81.]


In [57]:
#检测缺失值,为空就是 true，有数据就是ture
np.isnan([1,2,3])


array([False, False, False])

## Numpy的统计函数

In [62]:

arr=np.random.randint(1,20,8)
#求和
print(np.sum([1,2,3]))

6


In [63]:
#计算平均值
print(np.mean([1,2,3]))

2.0


In [67]:
#计算中位数
print(np.median([1,2,4,5]))
print(np.median([1,2,4]))

3.0
2.0


In [68]:
#计算标准差，方差
print(np.var([1,2,3]))#方差
print(np.std([1,2,3]))#标准差

0.6666666666666666
0.816496580927726


In [69]:
#计算最大最小值
print(np.max([1,2,3]))
print(np.min([1,2,3]))

3
1


In [70]:
#找到最大最小值的索引
print(np.argmax([1,2,3]))
print(np.argmin([1,2,3]))

2
0


In [71]:
#分位数
print(np.percentile([1,2,3,4,5,6,7,8,9,10,11,12],70))#七十分位数

8.7


In [74]:
#累计和，累积积
arr=np.array([1,2,3])
print(np.sum(arr))#累计和
print(np.cumsum(arr))#某一位的数字，加上它前面所有数字的和
print(np.cumprod(arr))#某一位的数字，乘以它前面的所有数字的积

6
[1 3 6]
[1 2 6]


## Numpy的比较函数

In [78]:
#大于
print(np.greater([3,4,5,6,7],4))#一个数组，一个标准，大于的回答TRUE。否则false
#小于
print(np.less([3,4,5,6,7],4))#同上
#等于
print(np.equal([3,4,5,6,7],4))#同上
print(np.equal([3,4,5],[6,7,8]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False False False]


In [82]:
#与或非
print(np.logical_and([1,0],[1,1]))#都为真才为真，否则是False
print(np.logical_or([1,0],[1,1]))#有一个为真即可
print(np.logical_not([1,0]))#对于一个数据而言

[ True False]
[ True  True]
[False  True]


In [83]:
#检查元素是否至少有一个为真
print(np.any([0,0,0,0,0]))
#是否全部为true
print(np.all([1,1,1,1,1]))


False
True


In [95]:
#自定义条件
#print(np.where(条件，符合条件，不符合条件))，符合条件就从前面取，否则从后面取
arr=np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))
score=np.random.randint(0,101,10)
#可以使用嵌套的np.where来做到多个条件
print(score)
print(np.where(score<60,'不及格',np.where(score<=80,'良好','优秀')))

[1 2 0 0 0]
[ 83  16  54  53  73  82  66  30 100  54]
['优秀' '不及格' '不及格' '不及格' '良好' '优秀' '良好' '不及格' '优秀' '不及格']


In [103]:
#排序函数
np.random.seed(0)
arr=np.random.randint(1,100,20)
print(arr)
print(np.sort(arr))#不改变原数组，原地排序
print(np.argsort(arr))#打印出，排序后数字原有的序号
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [104]:
#去重函数
print(np.unique(arr))


[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [105]:
#数组的拼接
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))#不能直接用+

[1 2 3 4 5 6]


In [107]:
#数组的分割
print(np.split(arr,[6,12,18]))#后面这个参数是切割位置的索引，要注意能分出来


[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [108]:
#调整数组的形状
print(np.reshape(arr,[4,5]))#可以把两行十列变为四行五列，但是要注意能等分


[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


# 学习阶段到此完结