# 一.ndaaray的特性

## 1.多维性：
支持，零维一维二维，类似于c中的数组

In [3]:
#引入numpy库
import numpy as np
from streamlit.hello import hello

#创建一个零维ndarray数组
arr=np.array(5)
print(arr.ndim)
print(arr)

0
5


In [5]:
#创建1维的数组
arr=np.array([1,2,3])
print(arr)
print(f"arr的维度是{arr.ndim}")

[1 2 3]
arr的维度是1


In [7]:
#创建一个2维的数组
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(f"arr的维度是{arr.ndim}")

[[1 2 3]
 [4 5 6]]
arr的维度是2


## 2.同质性：
如同数组，里面的元素必须是相同数据类型

In [10]:
arr=np.array([1,'hello'])
print(arr)

['1' 'hello']


注意上方的1是带有单引号的，是因为同质性，所以python将1转化为了字符串

In [11]:
arr=np.array([1,2.5])
print(arr)

[1.  2.5]


同理，此时为了保留更多数据，保留了2.5，将1转换为了1.

## 3.高效性：
同样类似与数组，是在内存中连续分配的，方便查找和管理

# 二.ndarray的属性:

1. shape:数组的行列数，用法：arr.shape
3. ndim:数组的维度，用法：arr.ndim
3. size:数组的个数，用法同上
4. dtype:数组元素的类型(整数，浮点数等),用法同上
5. T:转置：行变列，列变行
6. itemsize：单个元素占用的内存字节数
7. nbytes：数组总内存占用数：size*itemsize
8. flags:内存存储方式：是否连续存储

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状:',arr.shape)
print('数组的维度：:',arr.ndim)
print('数组的个数:',arr.size)
print('数组的类型:',arr.dtype)
print('数组的转置:',arr.T)
print('单个元素的占用内存:',arr.itemsize)
print('总内存：',arr.nbytes)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
数组的维度：: 2
数组的个数: 6
数组的类型: int64
数组的转置: [[1 4]
 [2 5]
 [3 6]]
单个元素的占用内存: 8
总内存： 48


# 三.ndarray的创建

## 1.基础方法

In [18]:
#基础的创建方法
list=[1,2,3]
arr=np.array(list)
print(arr)

[1 2 3]


In [19]:
arr1=np.copy(arr)#元素和初始的相同，但是不是同一个数组，原来那个不变
print(arr1)

[1 2 3]


## 2.预定义的定义

In [24]:
#预定义形状
#全0 全1 全初始化 固定值
#1.全零型
arr=np.zeros((2,3),dtype=int)#后面这个dtype是为了变成int型，不至于出现小数点
print(arr)
arr1=np.zeros((2,),dtype=int)#创建一维的全零数组
print(arr1)

[[0 0 0]
 [0 0 0]]
[0 0]


In [25]:
#全1型
arr=np.ones((2,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [26]:
#全初始化
arr=np.empty((2,3),dtype=int)#不推荐使用
print(arr)

[[0 0 0]
 [0 0 0]]


In [28]:
#全固定值
arr=np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [29]:
#附加用法
arr1=np.zeros_like(arr)#同arr格式一样，但由于是zeroslike，所以被填充为零a
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## 3.等差定义

In [30]:
arr=np.arange(1,10,2)#开始，结尾，步长
print(arr)

[1 3 5 7 9]


## 4.等间隔序列

In [32]:
arr=np.linspace(0,10,5)#开头，结尾，份数
print(arr)


[ 0  2  5  7 10]


## 5.对数间隔数列

In [33]:
arr=np.logspace(0,4,3,base=2)##开始，结束，份数，以这个为例，3代表0到四区间内找三个数，0，2，4，以它们作为base的指数，得出的结果
print(arr)

[ 1.  4. 16.]


## 6.特殊矩阵

In [34]:
#单位矩阵:主对角线为1，其余为零
arr=np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [35]:
#对角矩阵：主对角线上非零，其他全为零
arr=np.diag([1,2,3]#填的是主对角线上的元素
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [39]:
#随机数组的生成
#生成0到1之间的随机浮点数(均匀分布)
arr=np.random.rand(2,3)#每次运行都不一样
print(arr)

[[0.15084357 0.06578888 0.47945169]
 [0.34653485 0.48486993 0.99314173]]


In [40]:
#生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[4.82116213 4.68994684 4.50044316]
 [5.29162164 3.41117151 5.64772456]]


In [41]:
#生成指定范围区间的随机整数
arr=np.random.randint(3,30,(2,3))
print(arr)

[[ 5 22 10]
 [21 16 12]]


In [42]:
#生成随机数列(正态分布)(-
D:\Users\Yu\pythonlearning\PythonProject1\anaconda_projects
#两边小，中间大
arr=np.random.rand(2,3)
print(arr)

[[0.8895116  0.59252362 0.0216313 ]
 [0.31056908 0.73158565 0.68650965]]


In [43]:
#设置随机种子
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
